branches:
  only:
    - master

dist: bionic

language: php

sudo: required

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/symfony-bridge/.phpunit

env:
  global:
    - PHPUNIT_FLAGS="-v"
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
    - SYMFONY_VERSION="4.2.*" DB=mysql

matrix:
  fast_finish: true
  include:
    - php: '7.2'

before_install:
  - composer self-update

install:
  - export COMPOSER_ROOT_VERSION=dev-master
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer update
  - ./vendor/bin/simple-phpunit install

before_script:
  - php bin/console d:d:c --env=test
  - php bin/console d:s:c --env=test
  - php bin/console d:f:l --env=test --append
  - bin/console p:m:m
  - php bin/console p:m:m

script:
  - ./vendor/bin/simple-phpunit $PHPUNIT_FLAGS

