monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: critical
            handler: deduplicated
        deduplicated:
            type: deduplication
            handler: swift
        swift:
            type: swift_mailer
            from_email: 'no-reply@atypik.house'
            to_email: 'deozza@gmail.com'
            subject:    'An Error Occurred! %%message%%'
            level:      debug
            formatter:  monolog.formatter.html
            content_type: text/html